package main

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/Masterminds/semver"
	proto "github.com/codefly-dev/core/companions/proto"
)

// The nextjs agent generates the whole src/gen TypeScript tree — both the
// message types (*_pb.ts) and the service client — from the single
// protoc-gen-es plugin baked into the proto companion. Companion 0.0.11 ships
// protoc-gen-es 2.12.0; the older 0.0.10 floats es via ^2 and is missing the
// Go plugins buf needs. A consumer's checked-in tree must be generated by the
// same companion, so guard against regressing below 0.0.11.
func TestProtoCompanionMatchesConnectESToolset(t *testing.T) {
	image, err := proto.CompanionImage(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	tag, err := semver.NewVersion(image.Tag)
	if err != nil {
		t.Fatalf("cannot parse proto companion tag %q: %v", image.Tag, err)
	}
	if tag.LessThan(semver.MustParse("0.0.11")) {
		t.Fatalf("proto companion tag = %q, want >= 0.0.11 (protoc-gen-es 2.12.0)", image.Tag)
	}
}

func TestChangedGeneratedFilesDetectsAddsChangesAndRemovals(t *testing.T) {
	actual := t.TempDir()
	expected := t.TempDir()
	writeGeneratedTestFile(t, actual, "same_grpc_pb.ts", "same")
	writeGeneratedTestFile(t, expected, "same_grpc_pb.ts", "same")
	writeGeneratedTestFile(t, actual, "changed_grpc_pb.ts", "old")
	writeGeneratedTestFile(t, expected, "changed_grpc_pb.ts", "new")
	writeGeneratedTestFile(t, actual, "removed_grpc_pb.ts", "stale")
	writeGeneratedTestFile(t, expected, "added_grpc_pb.ts", "generated")
	writeGeneratedTestFile(t, actual, "saas/accounts/v1/user_settings_pb.ts", "producer-owned")
	writeGeneratedTestFile(t, expected, "saas/accounts/v1/user_settings_pb.ts", "different but producer-owned")

	changed, err := changedGeneratedFiles(actual, expected, "module/services/frontend/code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"module/services/frontend/code/src/gen/added_grpc_pb.ts",
		"module/services/frontend/code/src/gen/changed_grpc_pb.ts",
		"module/services/frontend/code/src/gen/removed_grpc_pb.ts",
	}
	if !reflect.DeepEqual(changed, want) {
		t.Fatalf("changed files = %v, want %v", changed, want)
	}
}

// A dry-run sync generates only the flat dependency client into the temporary
// tree, while the committed tree also carries the per-file protocol layout that
// the gRPC dependency's own buf.gen cross-writes (saas/accounts/v1/**, plus the
// shared google/** and buf/** deps). None of that foreign subtree is produced
// by this builder, so comparing the partial dry-run output against the full
// committed tree must report no drift. Mirrors module-saas-starter frontend.
func TestChangedGeneratedFilesIgnoresCrossWrittenDependencyTree(t *testing.T) {
	committed := t.TempDir()
	fresh := t.TempDir()

	// The one file this builder generates, byte-identical on regeneration.
	const flatClient = "saas-starter_accounts_grpc_pb.ts"
	writeGeneratedTestFile(t, committed, flatClient, "// protoc-gen-es\nflat client")
	writeGeneratedTestFile(t, fresh, flatClient, "// protoc-gen-es\nflat client")

	// The accounts service's buf.gen cross-writes these into src/gen; the shared
	// google/** and buf/** dependency output lives there too. Only committed.
	crossWritten := []string{
		"saas/accounts/v1/api_keys_pb.ts",
		"saas/accounts/v1/audit_pb.ts",
		"saas/accounts/v1/authentication_pb.ts",
		"saas/accounts/v1/authorization_pb.ts",
		"saas/accounts/v1/billing_pb.ts",
		"saas/accounts/v1/common_pb.ts",
		"saas/accounts/v1/identity_pb.ts",
		"saas/accounts/v1/organizations_pb.ts",
		"saas/accounts/v1/teams_pb.ts",
		"saas/accounts/v1/user_settings_pb.ts",
		"saas/accounts/v1/frontend_catalog.ts",
		"saas/billing/v1/jobs_pb.ts",
		"saas/frontend/v1/plugin_catalog.ts",
		"google/api/annotations_pb.ts",
		"google/api/http_pb.ts",
		"buf/validate/validate_pb.ts",
	}
	for _, relative := range crossWritten {
		writeGeneratedTestFile(t, committed, relative, "// protoc-gen-es\nproducer-owned")
	}

	changed, err := changedGeneratedFiles(committed, fresh, "module/services/frontend/code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	if len(changed) != 0 {
		t.Fatalf("cross-written dependency tree flagged as drift: %v", changed)
	}
}

func TestChangedGeneratedFilesTreatsMissingTreesAsEmpty(t *testing.T) {
	root := t.TempDir()
	expected := filepath.Join(root, "expected")
	writeGeneratedTestFile(t, expected, "client_grpc_pb.ts", "generated")
	changed, err := changedGeneratedFiles(filepath.Join(root, "missing"), expected, "code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(changed, []string{"code/src/gen/client_grpc_pb.ts"}) {
		t.Fatalf("changed files = %v", changed)
	}
}

func TestCleanDependencyGeneratedFilesPreservesProducerOwnedTrees(t *testing.T) {
	root := t.TempDir()
	writeGeneratedTestFile(t, root, "users_accounts_grpc_pb.ts", "owned")
	writeGeneratedTestFile(t, root, "saas/accounts/v1/user_settings_pb.ts", "producer-owned")
	writeGeneratedTestFile(t, root, "manual.ts", "product-owned")

	if err := cleanDependencyGeneratedFiles(root); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "users_accounts_grpc_pb.ts")); !os.IsNotExist(err) {
		t.Fatalf("owned dependency client still exists: %v", err)
	}
	for _, relative := range []string{"saas/accounts/v1/user_settings_pb.ts", "manual.ts"} {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(relative))); err != nil {
			t.Fatalf("preserve %s: %v", relative, err)
		}
	}
}

func TestServiceWorkspaceRelativePrefersPhysicalRepositoryPath(t *testing.T) {
	root := t.TempDir()
	physicalModule := filepath.Join(root, "module")
	service := filepath.Join(physicalModule, "services", "frontend")
	if err := os.MkdirAll(service, 0o755); err != nil {
		t.Fatal(err)
	}
	logicalModules := filepath.Join(root, "modules")
	if err := os.MkdirAll(logicalModules, 0o755); err != nil {
		t.Fatal(err)
	}
	logicalModule := filepath.Join(logicalModules, "saas-starter")
	if err := os.Symlink(physicalModule, logicalModule); err != nil {
		t.Skipf("cannot create symlink fixture: %v", err)
	}
	service = filepath.Join(logicalModule, "services", "frontend")
	if got := serviceWorkspaceRelative(root, service, "modules/saas-starter/services/frontend"); got != "module/services/frontend" {
		t.Fatalf("physical relative path = %q", got)
	}
	if got := serviceWorkspaceRelative(root, filepath.Dir(root), "fallback/service"); got != "fallback/service" {
		t.Fatalf("out-of-workspace fallback = %q", got)
	}
}

func writeGeneratedTestFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
