package main

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/Masterminds/semver"
	proto "github.com/codefly-dev/core/companions/proto"
	"github.com/stretchr/testify/require"
)

// The nextjs agent generates the whole src/gen TypeScript tree — both the
// message types (*_pb.ts) and the service client — from the single
// protoc-gen-es plugin baked into the proto companion. Companion 0.0.11 ships
// protoc-gen-es 2.12.0; the older 0.0.10 floats es via ^2 and is missing the
// Go plugins buf needs. A consumer's checked-in tree must be generated by the
// same companion, so guard against regressing below 0.0.11.
func TestProtoCompanionMatchesConnectESToolset(t *testing.T) {
	image, err := proto.CompanionImage(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	tag, err := semver.NewVersion(image.Tag)
	if err != nil {
		t.Fatalf("cannot parse proto companion tag %q: %v", image.Tag, err)
	}
	if tag.LessThan(semver.MustParse("0.0.11")) {
		t.Fatalf("proto companion tag = %q, want >= 0.0.11 (protoc-gen-es 2.12.0)", image.Tag)
	}
}

func TestChangedGeneratedFilesDetectsAddsChangesAndRemovals(t *testing.T) {
	actual := t.TempDir()
	expected := t.TempDir()
	writeGeneratedTestFile(t, actual, "same_grpc_pb.ts", "same")
	writeGeneratedTestFile(t, expected, "same_grpc_pb.ts", "same")
	writeGeneratedTestFile(t, actual, "changed_grpc_pb.ts", "old")
	writeGeneratedTestFile(t, expected, "changed_grpc_pb.ts", "new")
	writeGeneratedTestFile(t, actual, "removed_grpc_pb.ts", "stale")
	writeGeneratedTestFile(t, expected, "added_grpc_pb.ts", "generated")
	writeGeneratedTestFile(t, actual, "saas/accounts/v1/user_settings_pb.ts", "producer-owned")

	changes, err := generatedFileChanges(actual, expected)
	changed := generatedChangePaths(changes, "module/services/frontend/code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"module/services/frontend/code/src/gen/added_grpc_pb.ts",
		"module/services/frontend/code/src/gen/changed_grpc_pb.ts",
		"module/services/frontend/code/src/gen/removed_grpc_pb.ts",
	}
	if !reflect.DeepEqual(changed, want) {
		t.Fatalf("changed files = %v, want %v", changed, want)
	}
}

// Producer-owned protocol trees share src/gen with the agent's clients but
// must not become removals when absent from a frontend's staged output.
func TestChangedGeneratedFilesIgnoresCrossWrittenDependencyTree(t *testing.T) {
	committed := t.TempDir()
	fresh := t.TempDir()

	// The flat clients this builder generates: one byte-identical on
	// regeneration, one whose committed copy has genuinely drifted. Only the
	// drifted one must be reported, proving the builder still diffs its own
	// output while ignoring the cross-written subtree below.
	writeGeneratedTestFile(t, committed, "saas-starter_accounts_grpc_pb.ts", "// protoc-gen-es\nflat client")
	writeGeneratedTestFile(t, fresh, "saas-starter_accounts_grpc_pb.ts", "// protoc-gen-es\nflat client")
	writeGeneratedTestFile(t, committed, "saas-starter_billing_grpc_pb.ts", "// protoc-gen-es\nstale client")
	writeGeneratedTestFile(t, fresh, "saas-starter_billing_grpc_pb.ts", "// protoc-gen-es\nregenerated client")

	// The accounts service's buf.gen cross-writes these into src/gen; the shared
	// google/** and buf/** dependency output lives there too. Only committed.
	crossWritten := []string{
		"saas/accounts/v1/api_keys_pb.ts",
		"saas/accounts/v1/audit_pb.ts",
		"saas/accounts/v1/authentication_pb.ts",
		"saas/accounts/v1/authorization_pb.ts",
		"saas/accounts/v1/billing_pb.ts",
		"saas/accounts/v1/common_pb.ts",
		"saas/accounts/v1/identity_pb.ts",
		"saas/accounts/v1/organizations_pb.ts",
		"saas/accounts/v1/teams_pb.ts",
		"saas/accounts/v1/user_settings_pb.ts",
		"saas/accounts/v1/frontend_catalog.ts",
		"saas/billing/v1/jobs_pb.ts",
		"saas/frontend/v1/plugin_catalog.ts",
		"google/api/annotations_pb.ts",
		"google/api/http_pb.ts",
		"buf/validate/validate_pb.ts",
	}
	for _, relative := range crossWritten {
		writeGeneratedTestFile(t, committed, relative, "// protoc-gen-es\nproducer-owned")
	}

	changes, err := generatedFileChanges(committed, fresh)
	changed := generatedChangePaths(changes, "module/services/frontend/code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"module/services/frontend/code/src/gen/saas-starter_billing_grpc_pb.ts"}
	if !reflect.DeepEqual(changed, want) {
		t.Fatalf("changed files = %v, want %v", changed, want)
	}
}

func TestChangedGeneratedFilesTreatsMissingTreesAsEmpty(t *testing.T) {
	root := t.TempDir()
	expected := filepath.Join(root, "expected")
	writeGeneratedTestFile(t, expected, "client_grpc_pb.ts", "generated")
	changes, err := generatedFileChanges(filepath.Join(root, "missing"), expected)
	changed := generatedChangePaths(changes, "code/src/gen")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(changed, []string{"code/src/gen/client_grpc_pb.ts"}) {
		t.Fatalf("changed files = %v", changed)
	}
}

func TestPublishGeneratedFilesPreservesProducerOwnedTrees(t *testing.T) {
	root := t.TempDir()
	writeGeneratedTestFile(t, root, "users_accounts_grpc_pb.ts", "owned")
	writeGeneratedTestFile(t, root, "saas/accounts/v1/user_settings_pb.ts", "producer-owned")
	writeGeneratedTestFile(t, root, "manual.ts", "product-owned")

	changes, err := generatedFileChanges(root, t.TempDir())
	require.NoError(t, err)
	require.NoError(t, publishGeneratedFiles(root, changes))
	if _, err := os.Stat(filepath.Join(root, "users_accounts_grpc_pb.ts")); !os.IsNotExist(err) {
		t.Fatalf("owned dependency client still exists: %v", err)
	}
	for _, relative := range []string{"saas/accounts/v1/user_settings_pb.ts", "manual.ts"} {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(relative))); err != nil {
			t.Fatalf("preserve %s: %v", relative, err)
		}
	}
}

func TestServiceWorkspaceRelativePrefersPhysicalRepositoryPath(t *testing.T) {
	root := t.TempDir()
	physicalModule := filepath.Join(root, "module")
	service := filepath.Join(physicalModule, "services", "frontend")
	if err := os.MkdirAll(service, 0o755); err != nil {
		t.Fatal(err)
	}
	logicalModules := filepath.Join(root, "modules")
	if err := os.MkdirAll(logicalModules, 0o755); err != nil {
		t.Fatal(err)
	}
	logicalModule := filepath.Join(logicalModules, "saas-starter")
	if err := os.Symlink(physicalModule, logicalModule); err != nil {
		t.Skipf("cannot create symlink fixture: %v", err)
	}
	service = filepath.Join(logicalModule, "services", "frontend")
	if got := serviceWorkspaceRelative(root, service, "modules/saas-starter/services/frontend"); got != "module/services/frontend" {
		t.Fatalf("physical relative path = %q", got)
	}
	if got := serviceWorkspaceRelative(root, filepath.Dir(root), "fallback/service"); got != "fallback/service" {
		t.Fatalf("out-of-workspace fallback = %q", got)
	}
}

func writeGeneratedTestFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestPrivateGeneratedImportsNeverClaimSharedProducerFiles(t *testing.T) {
	actual := t.TempDir()
	writeGeneratedTestFile(t, actual, "saas/accounts/v1/api_pb.ts", "producer-owned")
	writeGeneratedTestFile(t, actual, "google/api/http_pb.ts", "first")
	output := map[string]generatedFile{
		"mod_accounts_grpc_pb.ts": {kind: "file", data: []byte("client")},
		"google/api/http_pb.ts":   {kind: "file", data: []byte("first")},
	}
	for _, content := range []string{"first", "second"} {
		output["google/api/http_pb.ts"] = generatedFile{kind: "file", data: []byte(content)}
		staged := t.TempDir()
		require.NoError(t, stageGeneratedClients(staged, output))
		changes, err := generatedFileChanges(actual, staged)
		require.NoError(t, err)
		require.NoError(t, publishGeneratedFiles(actual, changes))
		data, err := os.ReadFile(filepath.Join(actual, generatedPrivateDirectory, "google/api/http_pb.ts"))
		require.NoError(t, err)
		require.Equal(t, content, string(data))
		shared, err := os.ReadFile(filepath.Join(actual, "google/api/http_pb.ts"))
		require.NoError(t, err)
		require.Equal(t, "first", string(shared))
	}
	changes, err := generatedFileChanges(actual, t.TempDir())
	require.NoError(t, err)
	require.NoError(t, publishGeneratedFiles(actual, changes))
	require.NoFileExists(t, filepath.Join(actual, generatedPrivateDirectory, "google/api/http_pb.ts"))
	require.NoFileExists(t, filepath.Join(actual, "mod_accounts_grpc_pb.ts"))
	require.NoFileExists(t, filepath.Join(actual, generatedOwnershipFile))
	for _, name := range []string{"google/api/http_pb.ts", "saas/accounts/v1/api_pb.ts"} {
		require.FileExists(t, filepath.Join(actual, name))
	}
}

func TestGeneratedOutputRejectsProducerConflictsBeforePublishing(t *testing.T) {
	for _, kind := range []string{"file", "directory", "symlink"} {
		t.Run(kind, func(t *testing.T) {
			actual, expected := t.TempDir(), t.TempDir()
			writeGeneratedTestFile(t, actual, "app_backend_grpc_pb.ts", "old client")
			writeGeneratedTestFile(t, expected, "app_backend_grpc_pb.ts", "new client")
			writeGeneratedTestFile(t, expected, generatedPrivateDirectory+"/google/api/http_pb.ts", "new import")
			writeGeneratedTestFile(t, expected, generatedOwnershipFile, "[]")
			switch kind {
			case "file":
				writeGeneratedTestFile(t, actual, generatedPrivateDirectory+"/google/api/http_pb.ts", "producer-owned")
			case "directory":
				require.NoError(t, os.MkdirAll(filepath.Join(actual, generatedPrivateDirectory, "google/api/http_pb.ts"), 0755))
			case "symlink":
				require.NoError(t, os.Symlink(t.TempDir(), filepath.Join(actual, generatedPrivateDirectory)))

			}
			before, err := generatedFiles(actual)
			require.NoError(t, err)
			_, err = generatedFileChanges(actual, expected)
			require.ErrorContains(t, err, "producer-owned")
			after, err := generatedFiles(actual)
			require.NoError(t, err)
			require.Equal(t, before, after)
		})
	}
}

func TestGeneratedOwnershipRejectsPathsOutsideTheGeneratedTree(t *testing.T) {
	actual := t.TempDir()
	writeGeneratedTestFile(t, actual, generatedOwnershipFile, `["../producer.ts"]`)
	_, err := generatedFileChanges(actual, t.TempDir())
	require.ErrorContains(t, err, "invalid generated client path")
}
